### ISSUE TITLE
Frontend + backend?

### ISSUE THREAD

**Issue by pakk-minidose** [jandoubek/pvs-2020-lectures#1]
Budeme rozlišovat frontend a backend aplikace?
Nebo bude vše probíhat v internetovém prohlížeči?

**Comment by agehrtenab** [comment]
Přijde mi, že backend by asi byl zapotřebí pouze v případě, kdyby aplikace měla obsahovat nějaké solvery (MILP, CLP) k sestavení optimálního rozvrhu při dodržení zadaných podmínek nebo tak nějak. Pokud jde pouze o prohledávání, předpokládám, že stačí hostovat statická předzpracovaná data.

**Comment by SachCZ** [comment]
Pouze frontend.
