### ISSUE TITLE
Vizuální styl - barvy, fonty atd.

### ISSUE THREAD

**Issue by hetsko** [jandoubek/pvs-2020-lectures#13]
Navrhuji:

### Barvy
- Bílé pozadí, černý text
- Nějaké šedé odstíny na detaily
- Zvýraznění, některé detaily (hlavička) FJFI indigo ``#0365a9``

### Fonty
- Něco obyčejného bezpatkového
- Velikost a velká/malá písmena: přišlo mi to docela ok tak jak to je v tom nákresu #5

### Další
- Celkově bych se to snažil držet ploché a minimalistické.
- Logo FJFI je možné splašit [na stránkách FJFI](https://www.fjfi.cvut.cz/cz/media-a-verejnost/ke-stazeni) po přihlášení.
- ....

**Comment by SachCZ** [comment]
Jsem pro setnout ``#0365a9`` jako main theme color v material ui . Jsou tam nějaké theming options na které se budeme muset podívat do [dokumentace](https://material-ui.com/customization/theming/). Písmo bych nechal, he celkem vkusné a navhovali to lidi, kteří vědí o UI a UX víc než my. Obecně bych používal ten jejich styl, který má i nějakou [obecnou specifikaci](https://material.io/design/guidelines-overview) nezávislou na implementaci. Až se shodneme udělám user story.

**Comment by SachCZ** [comment]
Zatím zavírám, až na to znovu přijde můžeme reopen.
