### ISSUE TITLE
Všichni ready to go

### ISSUE THREAD

**Issue by SachCZ** [jandoubek/pvs-2020-lectures#15]
Předělal jsem README v [mainu](https://github.com/jandoubek/pvs-2020-lectures), nyní je zde popsáno jak začít vyvíjet. Prosím zareagujte na toto issue, až se vám podaří udělat první krůček v sekci vývoj, ať jsme všichni na stejné lodi, než začneme vyvíjet.

**Comment by hetsko** [comment]
Jsem na lodi.

**Comment by pakk-minidose** [comment]
Tutorial Reactu byl jasný, ve zbytku react.md jsem se začal už trochu ztrácet, ale snad se to vychytá za běhu

**Comment by SachCZ** [comment]
Jo ten zbytek react.md jsem psal spíš jako referenci. Důležitý je abychom se mohli alespoň základně bavit :+1:, takže super!

**Comment by SachCZ** [comment]
@agehrtenab už je taky ready to go, zavírám.
