### ISSUE TITLE
User stories mimo issues

### ISSUE THREAD

**Issue by SachCZ** [jandoubek/pvs-2020-lectures#16]
Navrhuji tvořit user stories mimo issues v sekci projekt - obdoba Trello. Bylo by hezké toto mít oddělené.

**Comment by hetsko** [comment]
> toto mít oddělené.

Nemám nic proti. Jen sám nemám asi dobrou představu, co psát tam a co do issues. User stories v projektu vyjadřují takové obecnější featury a cíle celého projektu, které si postupně odškrtáme, a tady v issues budeme řešit implementaci? Něco takového?

**Comment by SachCZ** [comment]
Tady je nějaký první template, co na mě vypadl v googlu. Nějaké další info je třeba [tady](https://medium.com/the-liberators/the-purpose-of-user-stories-in-scrum-840db325e8e3).

![image](https://user-images.githubusercontent.com/8849601/98052024-6d40df00-1e35-11eb-861d-8908ba831045.png)

**Comment by pakk-minidose** [comment]
To bych asi probral v pondělí, bude to vyžadovat rozsáhlejší diskuzi

**Comment by SachCZ** [comment]
Ta může probíhat tady. V pondělí to spíš shrneme. Kvůli tomu máme github.

**Comment by pakk-minidose** [comment]
OK.
Nebráním se tomu, ale z toho, co jsi napsal, mi není úplně jasné, jak by sis to představoval. Můžeš to prosím nějak rozvést?

**Comment by SachCZ** [comment]
Jasně, za to se omlovám. User stories slouží jako taková guide k čemu projekt směřuje. Mají daný template aby to bylo konzistentní. Zde je příklad user story:
- Já jako student jaderky chci mít možnost filtrovat předměty podle dne a času, abych mohl nalézt předmět, který se mi hodí do rozvrhu. Podmínka splnění: přijdu li na stránku vyhledávat a zadám li den a čas, dostanu seznam předmětů odpovídající kriteriím.

User stories jsou taková high level guide. Neříká to, jak přesně toho docílíme, protože to může být různé, ale jasně to definuje co chceme docílit.

Naproti tomu do issues bych psal, otázky, bugy, feature requesty (které třeba přerostou do user story) atd. Issues nemají pevně danou strukturu a je pod nimi diskuze. Lze zde řešit i low level věci např:
- Komponent SeachBar se na malé obrazovce zobrazuje špatně. Navrhuji změnit width z 1500px na 42px.

User stories jsou něco na čem jsem již dohodnutí a pracujeme na tom, případně to chceme udělat. Tomu odpovádají i sloupce mezi kterými lze user stories posouvat. Viz [projekt](https://github.com/jandoubek/pvs-2020-lectures/projects/1).

**Comment by pakk-minidose** [comment]
> Tomu odpovádají i sloupce mezi kterými lze user stories posouvat. Viz projekt.

Ano, to bylo to, co jsem potřeboval vidět.

V podstatě by to znamenalo to, že všechno, co teď označujeme labelem "TODO", bychom tam nějak přetransformovali, tj.

- "Já, jako vývojář, potřebuji nějaká toy data, se kterými můžu pracovat"

EDIT: samozřejmě nejenom to, taky tam musíme dát nějaké uživatelské funkce :-)

**Comment by SachCZ** [comment]
Více méně ano, ale některé TODO nejsou hodny samostatného user story z důvodů, které jsem uváděl (příliš specifické nebo naopak příliš vágní, bug fix, atd.) Ale ano, s tím co máme teď si myslím, že by většina TODOs mohla být user stories.

**Comment by SachCZ** [comment]
Ještě se omlouvám, ale vzhledem k tomu jak Github projekt funguje, jsem to ještě přehodil tak, že user stories jsou podmnožinou issues.

**Comment by hetsko** [comment]
Ok, je to hezčí. User story existují -> tohle asi zavíráme?
