### ISSUE TITLE
Výsledky vyhledávání - styl google vs. tabulka

### ISSUE THREAD

**Issue by hetsko** [jandoubek/pvs-2020-lectures#17]
Nabízí se dvě docela odlišné možnosti:
1. Blbuvzdorná uniformní tabulka
![table_example](https://user-images.githubusercontent.com/50210960/98044991-1680d880-1e28-11eb-8aae-ddb747c9d315.png)

1. Více stylizovaný výsledek (jako google)
![google_example](https://user-images.githubusercontent.com/50210960/98044844-d0c41000-1e27-11eb-9893-3958605c4dad.png)

Pište své názory, pro a proti.

**Comment by hetsko** [comment]
Na jednu stranu, 1. tabulka má určitou garanci větší přehlednosti a rozumně velkou hustotu informace na plochu. Ale je pravda, že je to takový suchý. A když by se tam cpalo víc než několik málo sloupců základních informací, tak to i tu přehlednost ztratí. Její uniformnost taky nedává možnost rozlišit věci podle důležitosti.

Takže jsem klidně i pro 2. google přístup, když ho nějak zformujeme, aby byl přehledný a šlo z něj vždycky pohodlně očima proskenovat výsledky podle těch důležitých věcí (ehm kredity). Nejlépe to trošku s tou tabulkou zkřížit.

Tohle by podle mě bylo třeba špatně (jen rychlý příklad, vím, že to bylo jen demo):
![bad_google_example](https://user-images.githubusercontent.com/50210960/98051690-b17faf80-1e34-11eb-9e86-fd9b0b951a6e.png)
- Výrazný je jen název předmětu a všechno ostatní je *ListItemText.secondary* a je to vidět až na druhý pohled. U googlu dává smysl, u předmětů ne. Chudák uživatel musí luštit malé šedé počty kreditů.
- Navíc to trochu neefektivně využívá prostor (směrem do strany). Výsledky jsou málo koncentrované a uživatel musí o to víc scrollovat.

**Comment by pakk-minidose** [comment]
Mně se osobně líbí víc varianta 1 - něco a lá Bílá kniha s filtrováním výsledků. S Bílou knihou umí pracovat všichni, takže by neměl být problém se zorientovat.

**Comment by SachCZ** [comment]
> Na jednu stranu, 1. tabulka má určitou garanci větší přehlednosti a rozumně velkou hustotu informace na plochu. Ale je pravda, že je to takový suchý. A když by se tam cpalo víc než několik málo sloupců základních informací, tak to i tu přehlednost ztratí. Její uniformnost taky nedává možnost rozlišit věci podle důležitosti.
> 
> Takže jsem klidně i pro 2. google přístup, když ho nějak zformujeme, aby byl přehledný a šlo z něj vždycky pohodlně očima proskenovat výsledky podle těch důležitých věcí (ehm kredity). Nejlépe to trošku s tou tabulkou zkřížit.
> 
> Tohle by podle mě bylo třeba špatně (jen rychlý příklad, vím, že to bylo jen demo):
> ![bad_google_example](https://user-images.githubusercontent.com/50210960/98051690-b17faf80-1e34-11eb-9e86-fd9b0b951a6e.png)
> 
> * Výrazný je jen název předmětu a všechno ostatní je _ListItemText.secondary_ a je to vidět až na druhý pohled. U googlu dává smysl, u předmětů ne. Chudák uživatel musí luštit malé šedé počty kreditů.
> * Navíc to trochu neefektivně využívá prostor (směrem do strany). Výsledky jsou málo koncentrované a uživatel musí o to víc scrollovat.

No ta myšlenka googlu je o tom, že člověk stejně hledá tak jeden dva předměty. A v každém případě si předmět člověk nezapíše hned po tom co vyděl jeho shrnutí. Proto jsou ty předměty rozklikávací. To, že by měli být kredity lépe vidět s tím naprosto souhlasím, ale to není neřešitelné. Nesouhlasím s tím, že má tabulka garanci větší přehlednosti. Já se v tabulkách ztrácím. Poslední věc je, že jsem pro hustotu informací na plochu minimalizovat a ne maximalizovat. Chceme aby stránka byla responzivní a ne overhelming.

**Comment by pakk-minidose** [comment]
Ad tabulka: předpokládám, že by ty názvy předmětů byly taky rozklikávací.

**Comment by hetsko** [comment]
Se tak obávám, že si to možná zase říká o nějaká menší **dema na více datech** (aspoň jedna stránka). Reálně to není velká část celého projektu, jde "jen" o pasivní zobrazování těch nalezených dat. Komponentová struktura Rectu tomu jen nahrává. Funčně/programátorsky nejsložitější na tom může být filtrovací záhlaví, které ale může být i stejné pro obojí, podobně jako ten vyskakovací dialog.

Na demech se to líp představí a člověk zjistí, jak se mu s tím pracuje. A třeba se utvrdíme, že to je čistě osobní preference jako ananas na pizze. Pak nebude nic jednoduššího, než **použít obojí** a předhodit tam uživateli někam do rohu přepínač (analogie je třeba zobrazení souborů ve složce - uživatel má možnosti seznam vs. malé ikony vs. dlaždice ...).

**Comment by SachCZ** [comment]
Prozatím uzavírám na základě diskuze a #23.
