### ISSUE TITLE
Výstup programu - pouze google nebo rovnou "nákupní košík"?

### ISSUE THREAD

**Issue by hypernek** [jandoubek/pvs-2020-lectures#18]
Myslím si, že jeden z hlavních důvodů proč to celé vyvíjíme je fakt, že KOS je na hledání a zápis zajímavých předmětů nepraktický. 

Velmi příjemná fíčura by bylo tedy něco jako "nákupní košík" předmětů. Fungovalo by to úplně stejně jak v e-shopech. V momentě kdy najdu něco, co mě zajímá, si můžu předmět "zapsat" - hodit do košíku. Ten pak půjde zobrazit (kliknutím na tlačítko vpravo nahoře) a v nejlepším případě exportovat rovnou do formy, kterou KOS schroustá.

Seznam předmětů/nákupní košík by pak byl ve stylu tabulky, tak jak bývá v KOSu. Vespod by byly součty kreditů, hodin, počet zkoušek apod. (což mně třeba v KOSu hodně chybí, tam je jenom součet kreditů za semestr). Také by tam bylo samozřejmě velkým červeným tlustým písmem napsáno "TOTO NENÍ ZÁPIS PŘEDMĚTŮ, NEZAPOMEŇTE SI SEZNAM PŘEKOPÍROVAT DO KOSU".

Toto souvisí s #17 - nákupní košík musí být ve stylu tabulky, jinak to nemá smysl. Výsledky hledání můžou potom být (což bude asi i dobré pro odlišení) v "google stylu".

Co si o tom myslíte?

**Comment by SachCZ** [comment]
To mi připadá jako skvělý nápad. Už jsme se trochu bavili o tom, že do kosu se dá zapsat pomocí get requestu, takže by to mělo být i celkem snadné. Každopádně si myslím, že je to celkem advanced feture a teď bych se měli soustředit na základní funkční verzi a toto přidat později. Už začínám trochu demagogický co se týče stylu google. ale nechápu, proč by to nutně muselo být ve stylu tabulky, prostě by měl u předmětu možnost přidat do košíku.

**Comment by SachCZ** [comment]
Vzhledem k tomu, že se nikdo nevyjádřil souhlasím s tím co teď vyvíjíš a zavírám.
