### ISSUE TITLE
Přehledně zobrazené výsledky hledání

### ISSUE THREAD

**Issue by SachCZ** [jandoubek/pvs-2020-lectures#23]
Já jako uživatel bych chtěl mít zobrazené výsledky vyhledávání přehlednou formou, tak abych se mohl zaměřit na to důležité (kredity).

Podmínka splnění: Všichni zúčastnění souhlasí s existující formou zobrazení.

**Comment by hetsko** [comment]
Přidána první verze (f0f6592) výsledků hledání.
1. Hlavní struktura je [``<Grid>``](https://material-ui.com/components/grid/). Přijde mi to smysluplné a taky se to dobře upravuje na reaktivní layout pro malá zařízení.
1. V commitnuté verzi jsou zatím dva návrhy seskupení/pořadí jednotlivých prvků, co mě napadly.
1. Pro kredity a hodiny jsem přidal grafický "bar" ukazatel, pro hodiny dvojbarevný (přednášky + cvika).
1. Jedním ze zobrazovaných prvků je i anotace jako krátký blok textu.

**Comment by SachCZ** [comment]
1. Myslím, že je to vpoho řešení
2. Vypadá takto, pro ostatní ať nemusí checkoutovat:
![image](https://user-images.githubusercontent.com/8849601/99313752-64520380-2860-11eb-948a-03a77fe80184.png)
Za mě druhá lepší. Líbilo by se mi kdyby tam bylo Rozvrhováno: Čtvrtek 13:30, ale to si možná v budoucnu zamýšlel.

3. Ty grafické bary mi připadají opravdu dobré, ale bude tam někde číslo ne? Je to nějaká chyba nebo je to tak myšlené? Určitě bych byl pro aby tam byla.
![image](https://user-images.githubusercontent.com/8849601/99313686-44224480-2860-11eb-9e30-d3acdb1e54c6.png)

**Comment by hetsko** [comment]
2. Jo, přidat čas by bylo dobrý. Pak taky vyřešit, co se tím rozvrhováno vlastně myslí - u prváckých předmětů s 2 přednáškama a 6 paralelkama cvik tam asi nebudeme psát všechno... Ale to je asi zase diskuze do budoucna.
3. Je to schovaný v tooltipu. Fakt, že to na tebe nevyskočilo asi značí, že to není moc dobrý řešení :D Na standupu jsem to chtěl ještě nějak okomentovat/prodiskutovat - druhá verze by byla, že místo "kr" tam bude naopak číslo a "kr" může být v tooltipu. Anebo tam bude celý nápis "3 kr".

**Comment by SachCZ** [comment]
3. V tooltipu jsem si toho všiml, ale to mi připadá málo. Jsem pro celý nápis 3 kr, případně i tooltip.

**Comment by jandoubek** [comment]
@jandoubek you should look into #21

**Comment by SachCZ** [comment]
@eskimo-kidnap @hypernek @agehrtenab Chtělo by to tedy prosím ať se ostatní vyjádří co nejdříve ať @hetsko ví co dál  :runner:

**Comment by pakk-minidose** [comment]
Co se týče nápisu, určitě bych tam dal jak ten počet kreditů, tak hodinovou dotaci ve formátu typu 2+2.
Jinak mně osobně se líbí více druhá varianta. Takhle z toho obrázku to není moc vidět, ale pak když je těch předmětů víc, tak se lépe vzájemně srovnávají.

**Comment by hypernek** [comment]
Mně přijdou obě varianty rozložení kreditů a hodinové dotace v jednom výsledků dobrý, asi bych se rozhodl podle toho, jak to bude fungovat v akci (jak bude příjemné s tím pracovat a orientovat se v těch výsledcích). 

Nápad se sytou a světlou červenou pro odlišení přednášek a cvičení se mi moc líbí, jenom bych tam k tomu (i ke kreditům) napsal i ty čísla, místa tam na to bude dost myslím.
