### ISSUE TITLE
Informace o kreditech v toy datech

### ISSUE THREAD

**Issue by SachCZ** [jandoubek/pvs-2020-lectures#26]
Já jako developer bych chtěl mít informaci o kreditech v toy datech, tak abych mohl implementovat relevantní části aplikace.

Podmínka splnění: json file s toy daty obsahuje informaci o kreditech.

**Comment by pakk-minidose** [comment]
Vyřešeno 2def5f9a21c091e325854b58c0fc4db4ae0cbcce
