### ISSUE TITLE
Test CreditsSlider

### ISSUE THREAD

**Issue by pakk-minidose** [jandoubek/pvs-2020-lectures#31]
Já jako vývojář bych se chtěl naučit s testovacím frameworkem pro React a JS a odzkoušet si ho.

Podmínka splnění: napíšu testík pro komponentu CreditsSlider.

**Comment by pakk-minidose** [comment]
@SachCZ myslel jsem, že testovat budeme všichni?

**Comment by SachCZ** [comment]
Jo to jo ale každý s tím bude hotov v jiný čas. Preferoval bych víc issues. Lepší je být konkrétnější.

**Comment by pakk-minidose** [comment]
OK

**Comment by pakk-minidose** [comment]
Možná bych dal ještě TODO issue testy, aby každý věděl, co bude dělat dál?

**Comment by SachCZ** [comment]
Sure to zní jako plán.
