### ISSUE TITLE
Testy

### ISSUE THREAD

**Issue by pakk-minidose** [jandoubek/pvs-2020-lectures#32]
Prosím @eskimo-kidnap @hypernek @hetsko , aby si pro svou React componentu připravili unit test, až ji budou mít hotovou.

Vedl bych to jako separátní user stories (viz #31)

**S aktuálním branchem nebo pull requestem rozhodně nemíchat**

**Comment by SachCZ** [comment]
O testech všichni tak nějak vědí.
