### ISSUE TITLE
Formát pro data

### ISSUE THREAD

**Issue by hetsko** [jandoubek/pvs-2020-lectures#4]
Navazuje na #3. Je potřeba zvolit formu "databáze" či datové struktury, se kterou bude pracovat vyhledávací mechanismus. A pak ta získaná data do té formy nacpat. Možnosti:
- SQL databáze (ale to asi odpadá, jestli podle #1 to celé bude fungovat v prohlížeči u uživatele?)
- Nějaká databázová knihovna v JavaScriptu (nemám představu)
- Nativní objekty v JavaScriptu, tj. ``data = {lectures: ["PVS", "MAN", "LAL"]}``
- ... ?

**Comment by agehrtenab** [comment]
Všechny faktory hovoří v neprospěch databázových řešení: 1) objem dat je malý, 2) data jsou statická, 3) algoritmy jsou potenciálně složité.

**Comment by pakk-minidose** [comment]
> Všechny faktory hovoří v neprospěch databázových řešení: 1) objem dat je malý, 2) data jsou statická, 3) algoritmy jsou potenciálně složité.

Souhlasím s @agehrtenab. Databáze by měla smysl, pokud by se data často měnila. Rozvrh půjde asi tahat z toho XML. Samozřejmě je otázkou, v jakém tvaru budou sylaby, ale pokud to taky bude nějaká webová stránka, tak si to podle mě ta appka může načítat on the go z toho webu.

Myslím, že si to ani nemusíme nijak trvale ukládat. Pravděpodobně by mohl stačit nějaký http požadavek a následné zpracování vrácené stránky pomocí regulárních výrazů s tím, že se ta data holt budou neustále znovu zpracovávat s každým zobrazením - z hlediska výkonu by to ale u dnešních počítaču neměl být problém.

Prozatimní řešení může být "načtu vše". Pak se může řešit průběžná komunikace s webem.

**Comment by eskimo-kidnap** [comment]
Souvisí také s #1

**Comment by SachCZ** [comment]
Přímý parse.
