### ISSUE TITLE
Potřeba setupnout protected branche

### ISSUE THREAD

**Issue by SachCZ** [jandoubek/pvs-2020-lectures#42]
Nemohu setupnout protected branche, protože nejsem admin repa. @jandoubek mohl bys prosím přidat pravidla pro branche main a develop?

V setting > branches je možnost add rule
![image](https://user-images.githubusercontent.com/8849601/100388109-fbba1200-3029-11eb-9be3-904a7af9f911.png)

Zde by prosím bylo ideální přidat rules pro větve main a devlop s následující configurací:
![image](https://user-images.githubusercontent.com/8849601/100388240-4d629c80-302a-11eb-9725-f453fbcaf94a.png)

nic víc než na screenshotu není asi zatím potřeba. V tabulce by mělo být něco jako **build (ubuntu-latest, 14.x)** a **test (ubuntu-latest, 14.x)**, tak tyto dvě prosím zaškrtnout.

**Comment by jandoubek** [comment]
Udelano

**Comment by pakk-minidose** [comment]
Můžeme uzavřít
