### ISSUE TITLE
Draft: Rozvržení hlavní stránky

### ISSUE THREAD

**Issue by hetsko** [jandoubek/pvs-2020-lectures#5]
Sestavit seznam hlavních uživatelských prvků a zobrazovaného obsahu (vyhledávací pole, výsledky, ...) a nahodit smysluplné rozmístění těchto prvků. Detaily ohledně složitějších komponent můžeme diskutovat v samostatných issues.

**Comment by pakk-minidose** [comment]
>Detaily ohledně složitějších komponent můžeme diskutovat v samostatných issues.

Založil jsem na to label GUI.

**Comment by hetsko** [comment]
# 1. Iterace

Nakreslil jsem středně promyšlený draft, abychom měli nějakou vizuální aproximaci cíle. Rozmýšlel jsem a zakreslil jsem:
- celkové rozdělení shora dolů: ``hlavička``, ``základní kritéria``, ``rozšířená``, ``výsledky``
- lokální rozmístění/pořadí prvků (tak nějak), snaha o smartphone-friendly
- #10 přepínač BS/NMS a zimní/letní v hlavičce
- #11 základní kritéria: zapomněl jsem na nějaká?
- rozšířená kritéria: nástřel, zabýval bych se tím až později
- #12 výsledky: nástřel, vymyslet, co dalšího se může zobrazovat
- #13 návrh barevného schéma (FJFI indigo ``#0365a9`` a nějaké šedé), font a velikosti?

K jednotlivým bodům otevírám nové issues, kde se o tom může diskutovat. Cílem je zhodnotit, co je blbost, co by bylo lepší jinak, co použijeme, jak to budeme implementovat atd.

---

![draft](https://user-images.githubusercontent.com/50210960/97791356-bd1f6c00-1bd1-11eb-8072-5fa32780facd.png)

**Comment by SachCZ** [comment]
1) dost dobrý :+1: 
2) musím se přiznat, že jsem měl trochu jinou představu. Určitě se mi libá přepínač zimní letní + bs/nms. Stejnou věc jako ty jsem si představoval pro dny a časy. Obdobně pak různé jednoduché přepínače. Co jsem si představoval jinak je prezentace dat a celý způsob vyhledávání. (viz #7). Jde mi hlavně o to nezahltit člověka, který na stránku přišel poprvé a chce co nejrychleji najít co hledá.  Ta klíčová slova bych si právě představoval už v rámci vyhledávání ve stejném okénku název nebo kód.

Jak je asi poznat z dema, moc se mi libí představa "google pro předměty". Takhle mi připadá, že to v něčem trochu supluje můj rozvrh, což mi nepřijde nutné.

**Comment by hetsko** [comment]
1. Google přístup ok, styl přepínačů na dny se mi taky líbí (lepší než check boxy). Klíčová slova sloučit s kódem a názvem taky nerozporuju.
1. K tomu zobrazování výsledků (nevím jak moc ses plánoval držet googlu):
    - Na googlu jsou horší a lepší výsledky, ty lepší jsou dřív v pořadí, kdežto u nás jsou všechny výsledky potenciálně dobré a uživatel si je musí sám ještě nějak přehrabat. Proto bych určitě přidal řazení (které jsem zamýšlel pro to tabulkové zobrazení). Ale to určitě nevynucuje tabulku, taky preferuju míň čar.
1. Uvidíme, co ještě přinese Mithril demo.

**Comment by SachCZ** [comment]
S řazením naprosto souhlasím.

**Comment by hetsko** [comment]
Už jsme to nějak prošli, rozcupovali na jednotlivé issues a user story. Dobrý pevný výchozí bod pro představu je teď Martinův základ a další iterace draftů už děláme pomocí kódu. Takže zavírám.
