### ISSUE TITLE
Celková délka vs. délka přednášky

### ISSUE THREAD

**Issue by pakk-minidose** [jandoubek/pvs-2020-lectures#51]
Při návrhu řešení #50 jsem narazil na to, že délka předmětu se dá interpretovat dvěma dost odlišnými způsoby.

1. Celkový čas za týden, co bych na předmětu měl strávit
2. Délka jednotlivého okénka v rozvrhu, tj. "jak dlouhá je podndělní přednáška"

Nyní otázka: **Co mám udělat s těma toy datama?** Budeme zatím dělat, že ten problém neexistuje používat tu jedinou délku, co tam je?

Nebo ke každému předmětu dáme položku "len" a "total_len"?

Při implementaci #3 na to pak bude potřeba myslet

**Comment by pakk-minidose** [comment]
Návrh řešení #52

**Comment by hetsko** [comment]
> 2. Délka jednotlivého okénka v rozvrhu, tj. "jak dlouhá je podndělní přednáška"

Co přesně tím myslíš? Ta délka v sylabách "2+2" by snad vždycky měla odpovídat tomu, že předmět dohromady v rozvrhu zabírá v součtu 4h, nebo ne? Jedinou výjimkou jsou věci jako diplomka, bakalářka, které nejsou nikde v rozvrhu, ale ty bych snad i do budoucna z dat vyignoroval úplně (nikdo to hledat asi nechce, k čemu, a jenom to přináší komplikace).

V té navržené opravě #52 máš třeba to POLO s Potůčkem `len=2, total_len=4`, které má inženýrství pevných látek tady https://rozvrh.fjfi.cvut.cz/tt_parts/NMS1 a jsou to normálně dvě přednášky, celkem 4 hodiny. Co je teda to `len`, délka pondělní přednášky? A co ta čtvrteční? (Tady jsou obě stejné, ale co tam, kde nebudou?) Jestli smysl toho má být umožnit situaci jako "hledám předmět, který nemá přednášky delší než 2h v kuse" tak to je už mi přijde jako trochu okrajová záležitost, kterou se teď zabývat asi nemusíme.

Ty otazníky za každou druhou větou nemyslím nijak útočně, jenom jsem trochu ztracen :D

**Comment by pakk-minidose** [comment]
No jasně, ale třeba analýza má dotaci 4+4, tj. celkově tě bude stát 8 hodin týdně, ale přitom máš 2 přednášky po 2 hodinách a 2 cvičení po 2 hodinách. Tj. hledat to podle celkové délky 8 nemá smysl.

Samozřejmě analýza je povinná, tak tu si asi do díry v rozvrhu hledat nebudeš. Ale dokážu si představit, že najdeš ve své díře v rozvrhu cvičení z volitelného předmětu, ale přednáška se ti kryje s něčím jiným, tak se rozhodneš chodit jenom na cvičení a přednášku si od někoho okopíruješ/naučíš se ze skript/něco.

> V té navržené opravě #52 máš ...

Ano, tak jsem to myslel.

Jediný údaj, co by se dal vypustit, je `total_len`, protože ten nezávisí na konkrétní formě rozvrhu a tudíž pro #50 třeba není relevantní. Ale osobně si myslím, že když už to máme taky nakóděné, tak se to tam může nechat - příliš mnoho vyhledávacích kritérií snad udělat nejde.

**Comment by hetsko** [comment]
Ok, vyhledávání ve stylu "stačí mi cvika" je dobré. Pak by možná bylo lepší to nějak lépe nazvat, pořád nevím jestli `len` teda znamená délku přednášky nebo cvik. Což by popravdě mohlo být různé. Ještě horší by to bylo, kdyby nějaký divnopředmět měl třeba 2 různě dlouhá cvika. Ale to je asi zase diskuze do budoucna, až budou reálná data.

Já se v tom trochu štourám hlavně abych měl přehled, co v těch toy datech je, když je pak používám taky v těch výsledcích vyhledávání.

**Comment by pakk-minidose** [comment]
Myslím, že už to můžeme uzavřít.
