### ISSUE TITLE
Ract example

### ISSUE THREAD

**Issue by SachCZ** [jandoubek/pvs-2020-lectures#7]
Ukázat **React** example, kde bude vyhledávací okno. Do kódu budou **nahardcodovat data**. V těchto datech umožnit textové vyhledávání (možná jen podle názvu) a rozumně zobrazit výsledek.

Toto obnáší i **založení React aplikace** a předvedení jejího spuštění pro lokální vývoj.

**Comment by agehrtenab** [comment]
Jenom ještě dotaz - hodíme oba příklady do nějakých vhodných podadresářů? Třeba něco jako já do demos/mithril a ty do demos/react, aby to nějak nekolidovalo (případně aby to pak ani jedno nepřekáželo s reálným vývojem).

**Comment by SachCZ** [comment]
Můžem udělat branch / fork. (branch asi stačí)

**Comment by agehrtenab** [comment]
OK, udělám to tedy asi takhle.

**Comment by pakk-minidose** [comment]
Souvisí s #2 (abychom tu měli pořádek)

**Comment by SachCZ** [comment]
Udělal jsem minimal react example na branch react-example. Hodil jsem to na firebase, odkaz je [híííííír](https://predmety-minimal.web.app/). Mějte prosím na paměti, že se jedná o **demo**, tj. nějaké **bugy** tam možná jsou, nepřestavuji si, že by toto byla jediná funkcianolita, předmětů tam mnoho není a **nepsal jsem** **media queries** (tj. jak to bude vypdata na malé obrazovce), **testy**, **dokumentaci** ani **prop types**. Koho by zajímalo jak to pustit u sebe, tak jsem tam nechal **default README**, které vzniklo při inicializaci. Konkrétněji bych toto řešil až se rozhodneme pro některou z variant. Máte-li zkušenosti s reactem, doporučuji si kód projít.

Pak jsou tam ještě věci, které mi vyloženě vadí, ale nechtěli se mi řešit, např. jak se chová aplikace při mačkání entru. Výhledově toto není problém a pro demo to není důležité.

**Comment by SachCZ** [comment]
Je použit [Material UI](https://material-ui.com/components/radio-buttons/) a Webstorm.

**Comment by SachCZ** [comment]
Uzavřít s #15.
