### ISSUE TITLE
Získat toy data z rozvrhu

### ISSUE THREAD

**Issue by pakk-minidose** [jandoubek/pvs-2020-lectures#9]
Vytáhnout z rozvrhu nějaká toy data

**Comment by agehrtenab** [comment]
![ttb_schema](https://user-images.githubusercontent.com/73476034/97858805-fc4bdb00-1cff-11eb-9bd5-bcb1473feb89.jpg)

Schéma databáze rozvrhového programu

**Comment by pakk-minidose** [comment]
Data mají tvar pole předmětů.
Každý předmět je reprezentován slovníkem s klíči
"day" "code" "lecturer" "room" "time" "length"
